apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8scourse-com-tls
spec:
  secretName: k8scourse-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8scourse.domalys.com
  dnsNames:
    - k8scourse.domalys.com
  acme:
    config:
      - http01:
          ingressClass: nginx
          domains:
            - k8scourse.domalys.com
